return {
  -- "tzachar/cmp-ai",
  -- dependencies = "nvim-lua/plenary.nvim",
  -- opts = function()
  --   local cmp_ai = require("cmp_ai.config")
  --
  --   cmp_ai:setup({
  --     max_lines = 200,
  --     provider = "Ollama",
  --     provider_options = {
  --       model = "llama3.2",
  --       auto_unload = true, -- Set to true to automatically unload the model when
  --       -- exiting nvim.
  --     },
  --     notify = true,
  --     notify_callback = function(msg)
  --       vim.notify(msg)
  --     end,
  --     run_on_every_keystroke = true,
  --     ignored_file_types = {
  --       -- default is not to ignore
  --       -- uncomment to ignore in lua:
  --       -- lua = true
  --     },
  --   })
  -- end,
}
